version: '3.4'

services:
  pow-shield:
    image: ruisiang/pow-shield
    environment:
      - PORT=3000
      - SESSION_KEY="abcdefghijklmnop"
      - WAF=on
      - POW=on
      - NONCE_VALIDITY=60000
      - INITIAL_DIFFICULTY=13
      - BACKEND_URL="http://example.com"
    expose:
      - '3000'
    ports:
      - '3000:3000'
